# CMake generated Testfile for 
# Source directory: /home/zihao/kaldi/src/nnet3
# Build directory: /home/zihao/kaldi/src/nnet3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(attention-test "/home/zihao/kaldi/src/nnet3/attention-test")
set_tests_properties(attention-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;124;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(convolution-test "/home/zihao/kaldi/src/nnet3/convolution-test")
set_tests_properties(convolution-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;125;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(natural-gradient-online-test "/home/zihao/kaldi/src/nnet3/natural-gradient-online-test")
set_tests_properties(natural-gradient-online-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;126;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-analyze-test "/home/zihao/kaldi/src/nnet3/nnet3-analyze-test")
set_tests_properties(nnet3-analyze-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;127;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-common-test "/home/zihao/kaldi/src/nnet3/nnet3-common-test")
set_tests_properties(nnet3-common-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;128;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-compile-test "/home/zihao/kaldi/src/nnet3/nnet3-compile-test")
set_tests_properties(nnet3-compile-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;129;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-compile-utils-test "/home/zihao/kaldi/src/nnet3/nnet3-compile-utils-test")
set_tests_properties(nnet3-compile-utils-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;130;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-component-test "/home/zihao/kaldi/src/nnet3/nnet3-component-test")
set_tests_properties(nnet3-component-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;131;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-compute-test "/home/zihao/kaldi/src/nnet3/nnet3-compute-test")
set_tests_properties(nnet3-compute-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;132;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-derivative-test "/home/zihao/kaldi/src/nnet3/nnet3-derivative-test")
set_tests_properties(nnet3-derivative-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;133;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-descriptor-test "/home/zihao/kaldi/src/nnet3/nnet3-descriptor-test")
set_tests_properties(nnet3-descriptor-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;134;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-example-test "/home/zihao/kaldi/src/nnet3/nnet3-example-test")
set_tests_properties(nnet3-example-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;135;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-graph-test "/home/zihao/kaldi/src/nnet3/nnet3-graph-test")
set_tests_properties(nnet3-graph-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;136;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-nnet-test "/home/zihao/kaldi/src/nnet3/nnet3-nnet-test")
set_tests_properties(nnet3-nnet-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;137;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-optimize-test "/home/zihao/kaldi/src/nnet3/nnet3-optimize-test")
set_tests_properties(nnet3-optimize-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;138;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-parse-test "/home/zihao/kaldi/src/nnet3/nnet3-parse-test")
set_tests_properties(nnet3-parse-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;139;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
add_test(nnet3-utils-test "/home/zihao/kaldi/src/nnet3/nnet3-utils-test")
set_tests_properties(nnet3-utils-test PROPERTIES  WORKING_DIRECTORY "/home/zihao/kaldi/src/nnet3" _BACKTRACE_TRIPLES "/home/zihao/kaldi/cmake/Utils.cmake;39;add_test;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;140;add_kaldi_test_executable;/home/zihao/kaldi/src/nnet3/CMakeLists.txt;0;")
